version: '3.7'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_PASSWORD: "adminerpw"
    # networks:
      # - pg14_test-db-net
      # - mysql8_test-db-net
    volumes:
      - ../dbfiles:/dbfiles
      - ./plugins-enabled:/var/www/html/plugins-enabled

# networks:
  # pg14_test-db-net:
  #   external: true
  # mysql8_test-db-net:
  #   external: true
